#!/usr/bin/env bash
# Start, stop, and inspect the local SGLang inference server.
#
# The harness freezes its client-side configuration, but the model server is
# operator-managed, so this script exists to make the server side reproducible
# too. Every launch is built from config/sglang.env and recorded, with the
# exact resolved arguments, under $SGLANG_LOG_DIR/<stamp>/.
#
# The server is launched from a YAML config file rather than a command line.
# That is deliberate: --api-key has no environment-variable form, and a key on
# the command line is readable by any user on the host through `ps -eo args`.
# The file carrying it is written 0600 into a private directory; the copy kept
# in the launch record has the key redacted.
#
# Usage:
#   scripts/sglang_server.sh config         print the resolved config (redacted)
#   scripts/sglang_server.sh serve          run in the foreground
#   scripts/sglang_server.sh start [secs]   run detached, then wait for ready
#   scripts/sglang_server.sh wait [secs]    block until /health answers
#   scripts/sglang_server.sh status         health, served model, pool sizes
#   scripts/sglang_server.sh stop           terminate the detached server
#   scripts/sglang_server.sh logs [-f|N]    show the current server log
#   scripts/sglang_server.sh pin            pin SGLANG_MODEL_REVISION
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "$ROOT/config/sglang.env"
if [[ -f "$ROOT/.env" ]]; then
  source "$ROOT/.env"
fi

VENV="$ROOT/${SGLANG_VENV:-.venv-sglang}"
PYTHON="$VENV/bin/python"
SGLANG="$VENV/bin/sglang"
LOG_DIR="$ROOT/${SGLANG_LOG_DIR:-runs/inference}"
PRIVATE="$LOG_DIR/.runtime"
PID_FILE="$LOG_DIR/server.pid"
CURRENT="$LOG_DIR/current"
BASE_URL="http://${SGLANG_HOST}:${SGLANG_PORT}"

die() { echo "error: $*" >&2; exit 1; }

require_venv() {
  [[ -x "$SGLANG" ]] || die "no SGLang venv at ${VENV#"$ROOT"/}. Run: make sglang-install"
}

# The pinned local snapshot when it is there, otherwise the Hub repo id (which
# is not revision-pinned, and which scripts/fetch_model.sh exists to avoid).
model_path() {
  local dir="${SGLANG_MODEL_DIR:-$HOME/models/${SGLANG_MODEL_REPO##*/}}"
  if [[ -f "$dir/config.json" ]]; then printf '%s' "$dir"; else printf '%s' "$SGLANG_MODEL_REPO"; fi
}

# Emit the launch configuration as YAML. With redact=1 the API key is replaced
# by a placeholder, which is the form kept in the launch record.
emit_config() {
  local redact="$1"
  local key="${LOCAL_API_KEY:-}"
  if [[ "$redact" == "1" && -n "$key" ]]; then key="<redacted>"; fi
  {
    echo "# Generated by scripts/sglang_server.sh from config/sglang.env."
    echo "# Do not edit: edit config/sglang.env and relaunch."
    echo "model-path: $(model_path)"
    [[ "$(model_path)" == "$SGLANG_MODEL_REPO" && -n "${SGLANG_MODEL_REVISION:-}" ]] \
      && echo "revision: ${SGLANG_MODEL_REVISION}"
    echo "served-model-name: ${SGLANG_SERVED_MODEL_NAME}"
    echo "trust-remote-code: true"
    echo "host: ${SGLANG_HOST}"
    echo "port: ${SGLANG_PORT}"
    echo "context-length: ${SGLANG_CONTEXT_LENGTH}"
    echo "kv-cache-dtype: ${SGLANG_KV_CACHE_DTYPE}"
    echo "mem-fraction-static: ${SGLANG_MEM_FRACTION_STATIC}"
    echo "attention-backend: ${SGLANG_ATTENTION_BACKEND}"
    echo "max-running-requests: ${SGLANG_MAX_RUNNING_REQUESTS}"
    echo "cuda-graph-max-bs-decode: ${SGLANG_CUDA_GRAPH_MAX_BS_DECODE}"
    echo "mamba-ssm-dtype: ${SGLANG_MAMBA_SSM_DTYPE}"
    echo "mamba-radix-cache-strategy: ${SGLANG_MAMBA_RADIX_CACHE_STRATEGY}"
    echo "reasoning-parser: ${SGLANG_REASONING_PARSER}"
    echo "tool-call-parser: ${SGLANG_TOOL_CALL_PARSER}"
    [[ "${SGLANG_ENABLE_STRICT_THINKING:-0}" == "1" ]] && echo "enable-strict-thinking: true"
    [[ "${SGLANG_ENABLE_CACHE_REPORT:-0}" == "1" ]] && echo "enable-cache-report: true"
    [[ -n "${SGLANG_SPECULATIVE_ALGORITHM:-}" ]] && echo "speculative-algorithm: ${SGLANG_SPECULATIVE_ALGORITHM}"
    [[ -n "${SGLANG_MAX_MAMBA_CACHE_SIZE:-}" ]] && echo "max-mamba-cache-size: ${SGLANG_MAX_MAMBA_CACHE_SIZE}"
    [[ -n "${SGLANG_MAX_TOTAL_TOKENS:-}" ]] && echo "max-total-tokens: ${SGLANG_MAX_TOTAL_TOKENS}"
    [[ -n "${SGLANG_CHUNKED_PREFILL_SIZE:-}" ]] && echo "chunked-prefill-size: ${SGLANG_CHUNKED_PREFILL_SIZE}"
    [[ -n "${SGLANG_MAMBA_FULL_MEMORY_RATIO:-}" ]] && echo "mamba-full-memory-ratio: ${SGLANG_MAMBA_FULL_MEMORY_RATIO}"
    [[ -n "$key" ]] && echo "api-key: ${key}"
    # Free-form escape hatch for one-off experiments; whatever it sets is
    # captured in the launch record like every other value.
    [[ -n "${SGLANG_EXTRA_YAML:-}" ]] && printf '%s\n' "$SGLANG_EXTRA_YAML"
    true
  }
}

# SGLang prints its whole server_args at startup, api_key included, so keeping
# the key out of argv is not enough: it lands in server.log, which is exactly
# the file someone attaches when asking for help. Overwrite it in place with a
# mask of the same length. Same length and same inode matter: the server holds
# the file open and keeps appending, and an edit that rewrote the file would
# silently detach its log from the path. The key travels to the helper through
# the environment, never argv.
scrub_log() {
  local log="$1"
  [[ -n "${LOCAL_API_KEY:-}" && -f "$log" ]] || return 0
  PICC_SCRUB="$LOCAL_API_KEY" python3 - "$log" <<'PY' || true
import os, sys
key = os.environ["PICC_SCRUB"].encode()
path = sys.argv[1]
data = open(path, "rb").read()
with open(path, "r+b") as handle:
    start = 0
    while (i := data.find(key, start)) >= 0:
        handle.seek(i); handle.write(b"*" * len(key)); start = i + len(key)
PY
}

# One directory per launch holding exactly what was run, so a run's inference
# configuration can be reconstructed later from the repository alone.
record_launch() {
  local stamp dir
  stamp="$(date -u +%Y%m%d-%H%M%SZ)"
  dir="$LOG_DIR/$stamp"
  mkdir -p "$dir"
  cp "$ROOT/config/sglang.env" "$dir/sglang.env"
  emit_config 1 > "$dir/config.yaml"
  {
    printf 'launched_at=%s\n' "$stamp"
    printf 'base_url=%s\n' "$BASE_URL"
    printf 'api_key_set=%s\n' "$([[ -n "${LOCAL_API_KEY:-}" ]] && echo yes || echo no)"
    printf 'sglang_version=%s\n' "$("$PYTHON" -c 'import sglang; print(sglang.__version__)' 2>/dev/null || echo unknown)"
    printf 'torch_version=%s\n' "$("$PYTHON" -c 'import torch; print(torch.__version__)' 2>/dev/null || echo unknown)"
    printf 'cuda_version=%s\n' "$("$PYTHON" -c 'import torch; print(torch.version.cuda)' 2>/dev/null || echo unknown)"
    printf 'gpu=%s\n' "$(nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader 2>/dev/null | head -1)"
  } > "$dir/launch.txt"
  ln -sfn "$stamp" "$CURRENT"
  printf '%s' "$dir"
}

run_server() {
  require_venv
  # Starting a second server over a live one fails on the port bind and then
  # overwrites server.pid with the dead attempt, leaving `stop` unable to find
  # the server that is actually running.
  if [[ "$(curl_auth -o /dev/null -w '%{http_code}' "$BASE_URL/health" 2>/dev/null || echo 000)" == "200" ]]; then
    die "a server is already answering on $BASE_URL; stop it first (make sglang-stop)"
  fi
  if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    die "pid $(cat "$PID_FILE") from a previous start is still alive; stop it first"
  fi
  # SGLang JIT-compiles kernels at first launch and shells out to `ninja` and
  # `nvcc` by name. Both are installed in the venv, but the venv is invoked by
  # absolute path rather than activated, so without this they are not on PATH
  # and the server dies part-way through startup with FileNotFoundError.
  local cuda_bin
  cuda_bin="$(dirname "$("$PYTHON" -c '
import pathlib, nvidia
for base in nvidia.__path__:
    for nvcc in pathlib.Path(base).rglob("bin/nvcc"):
        print(nvcc); raise SystemExit
' 2>/dev/null)" 2>/dev/null || true)"
  export PATH="$VENV/bin${cuda_bin:+:$cuda_bin}:$PATH"
  [[ -n "$cuda_bin" ]] && export CUDA_HOME="${cuda_bin%/bin}"
  # Bound the first-launch kernel build so it cannot be OOM-killed. See
  # SGLANG_BUILD_JOBS in config/sglang.env.
  # The harness timestamps everything in UTC; the server would otherwise log
  # in local time, nine hours off on this host, and lining a server event up
  # with a harness event means doing that arithmetic every time.
  export TZ=UTC
  export MAX_JOBS="${SGLANG_BUILD_JOBS:-4}"
  export FLASHINFER_NVCC_THREADS="${FLASHINFER_NVCC_THREADS:-1}"

  mkdir -p "$LOG_DIR"
  install -d -m 700 "$PRIVATE"
  local cfg="$PRIVATE/server.yaml"
  install -m 600 /dev/null "$cfg"
  emit_config 0 > "$cfg"

  local dir
  dir="$(record_launch)"
  echo "launch recorded in ${dir#"$ROOT"/}" >&2

  # --model-path is repeated on the command line because `sglang serve` picks
  # its backend (language model vs diffusion) from argv before it merges the
  # config file, and errors out if it is not there. The value is identical and
  # not a secret; the API key stays in the 0600 file.
  local path
  path="$(model_path)"
  # The log is private: until it is scrubbed it holds the API key.
  install -m 600 /dev/null "$dir/server.log"
  if [[ "$1" == "detached" ]]; then
    nohup "$SGLANG" serve --model-path "$path" --config "$cfg" >>"$dir/server.log" 2>&1 &
    echo $! > "$PID_FILE"
    echo "started pid $(cat "$PID_FILE"); log ${dir#"$ROOT"/}/server.log" >&2
  else
    "$SGLANG" serve --model-path "$path" --config "$cfg" 2>&1 | tee -a "$dir/server.log"
    scrub_log "$dir/server.log"
  fi
}

curl_auth() {
  if [[ -n "${LOCAL_API_KEY:-}" ]]; then
    curl -sS -H "Authorization: Bearer $LOCAL_API_KEY" "$@"
  else
    curl -sS "$@"
  fi
}

wait_ready() {
  local limit="${1:-1800}"
  local deadline=$(( SECONDS + limit ))
  while (( SECONDS < deadline )); do
    if [[ "$(curl_auth -o /dev/null -w '%{http_code}' "$BASE_URL/health" 2>/dev/null || echo 000)" == "200" ]]; then
      echo "ready after ${SECONDS}s"
      [[ -e "$CURRENT" ]] && scrub_log "$(readlink -f "$CURRENT")/server.log"
      return 0
    fi
    if [[ -f "$PID_FILE" ]] && ! kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
      [[ -e "$CURRENT" ]] && scrub_log "$(readlink -f "$CURRENT")/server.log"
      echo "server exited before becoming ready; last lines of its log:" >&2
      tail -n 25 "$(readlink -f "$CURRENT")/server.log" >&2 || true
      return 1
    fi
    sleep 5
  done
  echo "timed out after ${limit}s waiting for $BASE_URL/health" >&2
  return 1
}

case "${1:-status}" in
  config)  emit_config 1 ;;
  serve)   run_server foreground ;;
  start)   run_server detached; wait_ready "${2:-1800}" ;;
  wait)    wait_ready "${2:-1800}" ;;
  stop)
    [[ -f "$PID_FILE" ]] || die "no pid file at ${PID_FILE#"$ROOT"/}"
    pid="$(cat "$PID_FILE")"
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid"
      for _ in $(seq 60); do kill -0 "$pid" 2>/dev/null || break; sleep 1; done
      kill -0 "$pid" 2>/dev/null && kill -9 "$pid" || true
      echo "stopped $pid"
      [[ -e "$CURRENT" ]] && scrub_log "$(readlink -f "$CURRENT")/server.log"
    else
      echo "pid $pid is not running"
    fi
    rm -f "$PID_FILE"
    ;;
  status)
    echo "endpoint   $BASE_URL"
    code="$(curl_auth -o /dev/null -w '%{http_code}' "$BASE_URL/health" 2>/dev/null || echo 000)"
    echo "health     $code"
    [[ "$code" == "200" ]] || exit 1
    curl_auth "$BASE_URL/get_model_info" 2>/dev/null | "$PYTHON" -c '
import json, sys
d = json.load(sys.stdin)
print(f"{"model":<24} {d.get("model_path")}")
print(f"{"served":<24} {d.get("served_model_name") or d.get("model_path")}")
' 2>/dev/null || true
    curl_auth "$BASE_URL/get_server_info" 2>/dev/null | "$PYTHON" -c '
import json, sys
d = json.load(sys.stdin)
a = d.get("server_args") or {}
for k in ("context_length", "max_total_num_tokens", "max_running_requests",
          "attention_backend", "kv_cache_dtype", "mamba_ssm_dtype",
          "mem_fraction_static", "reasoning_parser", "tool_call_parser"):
    v = d.get(k, a.get(k))
    if v is not None:
        print(f"{k:<24} {v}")
' 2>/dev/null || true
    ;;
  logs)
    [[ -e "$CURRENT" ]] || die "no recorded launch yet"
    if [[ "${2:-}" == "-f" ]]; then tail -f "$(readlink -f "$CURRENT")/server.log"
    else tail -n "${2:-80}" "$(readlink -f "$CURRENT")/server.log"; fi
    ;;
  pin)
    require_venv
    rev="$("$PYTHON" - "$SGLANG_MODEL_REPO" <<'PY'
import sys
from huggingface_hub import HfApi
print(HfApi().model_info(sys.argv[1]).sha)
PY
)"
    [[ -n "$rev" ]] || die "could not resolve a revision for $SGLANG_MODEL_REPO"
    "$PYTHON" - "$ROOT/config/sglang.env" "$rev" <<'PY'
import pathlib, re, sys
path, rev = pathlib.Path(sys.argv[1]), sys.argv[2]
path.write_text(re.sub(r"^SGLANG_MODEL_REVISION=.*$",
                       f"SGLANG_MODEL_REVISION={rev}",
                       path.read_text(), flags=re.M))
PY
    echo "pinned SGLANG_MODEL_REVISION=$rev"
    ;;
  *) die "unknown subcommand: $1" ;;
esac
